
import subprocess
import sys


def execute_plan(plan):
    """
    Execute only explicitly allowlisted safe actions.

    Polaris never executes arbitrary commands generated by Gemma.
    """

    if not plan:
        return {
            "message": "❌ No action plan received.",
            "output": "",
        }

    plan_lower = plan.lower()

    # ---------------------------------------------------------
    # SAFE ACTION: Install Python requests package
    # ---------------------------------------------------------
    if "pip install requests" in plan_lower or (
        "install" in plan_lower and "requests" in plan_lower
    ):
        try:
            result = subprocess.run(
                [
                    sys.executable,
                    "-m",
                    "pip",
                    "install",
                    "requests",
                ],
                capture_output=True,
                text=True,
                timeout=120,
            )

            output = result.stdout

            if result.stderr:
                output += "\n" + result.stderr

            if result.returncode == 0:
                return {
                    "message": "✅ Human-approved action executed: requests was installed successfully.",
                    "output": output,
                }

            return {
                "message": "❌ The approved installation failed.",
                "output": output,
            }

        except subprocess.TimeoutExpired:
            return {
                "message": "❌ Installation timed out.",
                "output": "pip install requests exceeded the 120-second limit.",
            }

        except Exception as exc:
            return {
                "message": f"❌ Action failed: {exc}",
                "output": str(exc),
            }

    # ---------------------------------------------------------
    # Nothing matched the allowlist
    # ---------------------------------------------------------
    return {
        "message": (
            "⚠️ Polaris did not execute this action because "
            "it is not on the safe-action allowlist."
        ),
        "output": "No command was executed.",
    }


def verify_result(output, diagnosis):
    """
    Basic local verification for the requests demo.
    """

    if not output:
        return "⚠️ No tool output was available for verification."

    output_lower = output.lower()

    if (
        "successfully installed" in output_lower
        or "successfully installed" in output_lower
        or "successfully installed" in diagnosis.lower()
    ):
        return "✅ Verification: the approved installation appears to have completed successfully."

    if "requests" in output_lower and (
        "successfully" in output_lower
        or "already satisfied" in output_lower
    ):
        return "✅ Verification: the requests package appears to be installed."

    if "error" in output_lower or "failed" in output_lower:
        return "❌ Verification: the action appears to have failed."

    return (
        "ℹ️ Verification: the tool returned output, but Polaris "
        "cannot confidently confirm the final state."
    )
